import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#e1bfb5",
        "on-primary-fixed": "#390c00",
        "surface-variant": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        "surface-tint": "#ab3500",
        "primary-fixed-dim": "#ffb59d",
        "primary-fixed": "#ffdbd0",
        "on-tertiary-container": "#003744",
        "tertiary-fixed": "#b5ebff",
        tertiary: "#00677e",
        background: "#f7f4ee",
        "surface-dim": "#dcd9d9",
        "on-secondary-container": "#00536f",
        "tertiary-container": "#00a7cb",
        surface: "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "on-background": "#1c1b1b",
        "status-developing": "#8a8578",
        "on-tertiary-fixed": "#001f28",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#004d67",
        "on-surface": "#1c1b1b",
        "surface-container": "#f0edec",
        "primary-container": "#ff6b35",
        "secondary-fixed": "#c1e8ff",
        error: "#ba1a1a",
        "secondary-container": "#57cafe",
        "surface-bright": "#fcf9f8",
        "inverse-on-surface": "#f3f0ef",
        "secondary-fixed-dim": "#74d1ff",
        "on-primary-container": "#5f1900",
        "on-secondary-fixed": "#001e2b",
        "inverse-primary": "#ffb59d",
        "tertiary-fixed-dim": "#59d5fb",
        "on-surface-variant": "#594139",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "status-undeveloped": "#2a2a2a",
        "error-container": "#ffdad6",
        border: "#e8e2d8",
        "on-error-container": "#93000a",
        "text-muted": "#77736d",
        secondary: "#006687",
        primary: "#ab3500",
        "surface-container-high": "#eae7e7",
        "on-primary-fixed-variant": "#832600",
        "on-tertiary-fixed-variant": "#004e60",
        "on-tertiary": "#ffffff",
        outline: "#8d7168",
        "inverse-surface": "#313030",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        gutter: "24px",
        "stack-lg": "32px",
        unit: "4px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        caption: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
